apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rocketmq-operator
  template:
    metadata:
      labels:
        name: rocketmq-operator
    spec:
      serviceAccountName: rocketmq-operator
      containers:
        - name: rocketmq-operator
          # Replace this with the built image name
          #image: harbor.myquanwei.com/library/rocketmq-operator:1.0.0
          image: zeratullich/rocketmq-operator:2.0.0
          command:
          - rocketmq-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rocketmq-operator"
